// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cppoverlaps
Rcpp::DataFrame cppoverlaps(const Rcpp::DataFrame& df1, const Rcpp::DataFrame& df2);
RcppExport SEXP _roverlaps_cppoverlaps(SEXP df1SEXP, SEXP df2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type df1(df1SEXP);
    Rcpp::traits::input_parameter< const Rcpp::DataFrame& >::type df2(df2SEXP);
    rcpp_result_gen = Rcpp::wrap(cppoverlaps(df1, df2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_roverlaps_cppoverlaps", (DL_FUNC) &_roverlaps_cppoverlaps, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_roverlaps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
